### ISSUE TITLE
[Bug]: url-list.txt is empty

### ISSUE THREAD

**Issue by iandol** [chrisgrieser/alfred-neovim-utilities#1]
### Bug Description

I am just trying v1.0. I have nvim installed via homebrew here: `/opt/homebrew/bin/nvim`. When I run `:vim` see debug log below.

But that file is empty and trying `:h` results in no results and the fallback to a google search:

![Screenshot 2023-01-28 at 12 38 31](https://user-images.githubusercontent.com/153905/215242313-fad57a89-c859-49eb-b118-cf1b9c7b01d8.png)

### Debugging Log

```Text
[12:33:41.153] Neovim Utilities[Run Script] Passing output 'Downloading doc files…
###########################################################################################################################
Parsing doc files…
Writing Index & cleaning up…
3/Users/ian/Library/ApplicationSupport/Alfred/WorkflowData/de.chris-grieser.neovim-utilities/url-list.txt entries.
' to Post Notification
[12:33:41.155] Neovim Utilities[Post Notification] Processing complete
```
```


### Workflow Configuration

![Screenshot 2023-01-28 at 12 40 06 copy](https://user-images.githubusercontent.com/153905/215242469-8e70630f-1f6d-417a-9cdc-4ec56bb662e5.png)


### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-neovim-utilities/releases/latest) of this workflow.

**Comment by chrisgrieser** [comment]
hmmm, I cannot reproduce the problem, and I cannot really think of a reason why this would not work.

Is this the first time you are using the workflow, or did you update from an older version where it used to work correctly?

Only thing you could try is to try [run the script that creates the URL list](https://github.com/chrisgrieser/alfred-neovim-utilities/blob/main/scripts/neovim-docs-index-creation.sh) manually (replacing the cache location at line 5) and see at which point in your device it breaks

**Comment by iandol** [comment]
Yes it's the first time I used it. Reading through the script I see it uses githubusercontent.com which is blocked in China and isn't always included in VPN whitelists. If I make sure my VPN is working with that server and run the script manually then I could get the script to works. I'll close as this is a problem due to the Chinese firewall... Thanks Chris!

**Comment by vitorgalvao** [comment]
Apologies for the off-topicness, @chrisgrieser, but I want to ask @iandol what’s that theme. You both have interesting ones! I especially like the contrast between one feeling very computery and the other bookish.

**Comment by iandol** [comment]
@vitorgalvao -- I really love Slab Serif fontfaces, though as my theme uses a proprietary font (Graublau Slab), I exported it using some available alternatives (`brew install font-bitter font-zilla slab`):

[Slab Serif Dark.zip](https://github.com/chrisgrieser/alfred-neovim-utilities/files/10528855/Slab.Serif.Dark.zip)
